name: inovola_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Responsive & Design
  flutter_screenutil: ^5.9.3
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  # Dependency Injection
  get_it: ^7.6.0
  # Network
  cached_network_image: ^3.4.1
  # UI
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  # Animations
  flutter_animate: ^4.5.2
  # Utils
  image_picker: ^1.1.1
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0   

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner:   
  hive_generator: ^2.0.1    

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
